//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhuGuan.AnQuan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseAnalysisInfo
    {
        public CaseAnalysisInfo()
        {
            this.DelFlag = 1;
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime SubTime { get; set; }
        public short DelFlag { get; set; }
        public string Remark { get; set; }
    }
}
