//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhuGuan.AnQuan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiddenDangerInfo
    {
        public HiddenDangerInfo()
        {
            this.DelFlag = 1;
        }
    
        public int HDId { get; set; }
        public System.DateTime InspDate { get; set; }
        public string InspUnit { get; set; }
        public string Zrdw { get; set; }
        public string Zrbz { get; set; }
        public string HidProblem { get; set; }
        public string ReformMeasure { get; set; }
        public Nullable<System.DateTime> PreTime { get; set; }
        public string AchievedDesp { get; set; }
        public string ReasonNotCompleted { get; set; }
        public string TraceMan { get; set; }
        public string Class2 { get; set; }
        public string Level2 { get; set; }
        public string Remark { get; set; }
        public Nullable<short> DelFlag { get; set; }
    }
}
