//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhuGuan.AnQuan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Pwd = "123";
            this.DelFlag = 1;
            this.IsVerified = 0;
            this.RoleInfo = new HashSet<RoleInfo>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public short DelFlag { get; set; }
        public string Remark { get; set; }
        public short IsVerified { get; set; }
        public int UnitInfoId { get; set; }
    
        public virtual UnitInfo UnitInfo { get; set; }
        public virtual ICollection<RoleInfo> RoleInfo { get; set; }
    }
}
